server:
  port: 8090
moneda:
  tipocambio:
    sol:
      solADolarUsa: 0.29
      solAPesoMexicano: 6.50
    dolarUsa:
      dolarUsaASol: 3.5
      dolarUsaAPesoMexicano: 22.73
    pesosMexicano:
      pesosMexicanoASol: 0.15
      pesosMexicanoADolarUsa: 0.044
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reactive
    username: moneda
    password: moneda
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**

#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
